// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5W2GGBLY_g_dps_CYL4KwnLdxSmxzud4',
    appId: '1:1006579105538:android:5748d824815d27ca4a4c1b',
    messagingSenderId: '1006579105538',
    projectId: 'sst-namix',
    databaseURL: 'https://sst-namix-default-rtdb.firebaseio.com',
    storageBucket: 'sst-namix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLm7x-E939Laqzu0pLOZtum8qHc7SIqQ',
    appId: '1:1006579105538:ios:0e147b8e5b04911e4a4c1b',
    messagingSenderId: '1006579105538',
    projectId: 'sst-namix',
    databaseURL: 'https://sst-namix-default-rtdb.firebaseio.com',
    storageBucket: 'sst-namix.appspot.com',
    iosClientId: '1006579105538-qbaka4f187m965o1jlc7g678f4e9bauu.apps.googleusercontent.com',
    iosBundleId: 'com.namix.sst.namix',
  );
}
